// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_0qsBMQfD0pjn9LdTib_bqt_9TeUA9rU',
    appId: '1:675968559791:web:3c7b94f9d3f4ff11c0825a',
    messagingSenderId: '675968559791',
    projectId: 'ecommerce-app-9029e',
    authDomain: 'ecommerce-app-9029e.firebaseapp.com',
    storageBucket: 'ecommerce-app-9029e.firebasestorage.app',
    measurementId: 'G-VW02Z9SKM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl1wIUwQod75BpaOsjbmAJbu9xKFZt0oE',
    appId: '1:675968559791:android:bb6245acaf4913c3c0825a',
    messagingSenderId: '675968559791',
    projectId: 'ecommerce-app-9029e',
    storageBucket: 'ecommerce-app-9029e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB-KWZaduSvmsWeooTEYWxAV8ivtcZKYY',
    appId: '1:675968559791:ios:e85702222010271bc0825a',
    messagingSenderId: '675968559791',
    projectId: 'ecommerce-app-9029e',
    storageBucket: 'ecommerce-app-9029e.firebasestorage.app',
    iosClientId: '675968559791-mbg6s9hhfjfprisn2h3rtt21qn2i0ade.apps.googleusercontent.com',
    iosBundleId: 'com.example.usta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB-KWZaduSvmsWeooTEYWxAV8ivtcZKYY',
    appId: '1:675968559791:ios:e85702222010271bc0825a',
    messagingSenderId: '675968559791',
    projectId: 'ecommerce-app-9029e',
    storageBucket: 'ecommerce-app-9029e.firebasestorage.app',
    iosClientId: '675968559791-mbg6s9hhfjfprisn2h3rtt21qn2i0ade.apps.googleusercontent.com',
    iosBundleId: 'com.example.usta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_0qsBMQfD0pjn9LdTib_bqt_9TeUA9rU',
    appId: '1:675968559791:web:dff83cb5be882668c0825a',
    messagingSenderId: '675968559791',
    projectId: 'ecommerce-app-9029e',
    authDomain: 'ecommerce-app-9029e.firebaseapp.com',
    storageBucket: 'ecommerce-app-9029e.firebasestorage.app',
    measurementId: 'G-KM224V5TKL',
  );
}
